Attempting to Fix Error Uploading
The error we are attempting to fix:
Error: Could not determine newPath for image

Believe to be caused by the Metadata property of PutObjectParams and so trying a different class